variables:
  DEPLOY_PATH: "/var/www/pplbuild"
  NGINX_USER_GROUP: "apache:"

building:
  stage: build

  script:
    - git reset --hard
    - git pull origin "$CI_COMMIT_BRANCH"
    - composer install -q
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate --seed
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan storage:link

publishing:
  stage: deploy

  variables:
    GIT_CLEAN_FLAGS: none

  only:
    - master
    - develop

  script:
    - cd ..
    - sudo rm -rf "/var/www/$CI_PROJECT_NAME"
    - sudo cp -r "$CI_PROJECT_NAME" /var/www/
    - sudo rm -rf "$DEPLOY_PATH"
    - sudo mv "/var/www/$CI_PROJECT_NAME" "$DEPLOY_PATH"
    - sudo chown -R "$NGINX_USER_GROUP" "$DEPLOY_PATH"
    - sudo restorecon -R /var/www/
